# Generated by Django 3.1.5 on 2021-02-07 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-created_time']},
        ),
        migrations.RemoveField(
            model_name='blog',
            name='content',
        ),
    ]
