# Generated by Django 3.1.5 on 2021-02-07 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210207_1728'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
