# Generated by Django 3.1.5 on 2021-02-19 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_auto_20210219_2234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='parents',
            new_name='parent',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='parent_id',
        ),
    ]
