# Generated by Django 3.1.5 on 2021-02-19 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_auto_20210219_2235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='parent',
            new_name='parents',
        ),
    ]
